### ISSUE TITLE
📜highlight styles for <code> tag is missing in slides (highlighting keywords in text)

### ISSUE THREAD

**Issue by yilmazdurmaz** [hedyorg/hedy#6117]
**Describe the issue**

This happens in slides for English and Turkish at least.

I could not yet check them all, but they should be sharing a single style in the template, so I expect this in all slides.

The following from "build-tools/heroku/tailwind/styles.css", for example, could solve the problem if added in the template.
````css
code {
  @apply font-mono inline rounded py-1 px-2 font-normal;
  background: #272822 !important;
  color: #ff6188;
  font-size: 90%;
}
````

For the moment, I am adding a visual indicator to my translations. that is, I am quoting keywords like this `"{print}"`. Ugly in the source but looks good on the page. Also, it will still be looking nice if you fix the highlighting.

Below, I added screenshots of current and expected looks of keywords in slides.

**Add a screenshot (optional)**

![Image](https://github.com/user-attachments/assets/034f31d7-0bef-4e71-8f8c-d6d4c1deeb31)

![Image](https://github.com/user-attachments/assets/7d057554-6243-440c-b061-ab6327e827f7)

**Expected text**

![Image](https://github.com/user-attachments/assets/78bdb4b5-865e-4c06-8f6f-a43f39a52ddb)

**Temporary solution**
![Image](https://github.com/user-attachments/assets/77eeaaf5-87ed-45dc-846f-4925bc53e793)
